[package]
name = "log-analyzer"
version = "0.1.0"
authors = ["Jan Schulte <hello@unexpected-co.de>"]

[dependencies]
clap = "2"
serde_json = "1.0"
serde_derive = "1.0.75"
serde = "1.0.75"
regex = "1"
itertools = "0.7.3"